### PR TITLE
Styling for the Remote Flashing Page

### PR DESCRIPTION
**Pull request by kevincheng0**
A lot of changes and additions:
-Most of the styling for the remote flashing page, some stuff like the form input states and warning modals will come in a later ticket
- Fixed the width of sidebar to be constant 400px as seen on Figma
- Changed sidebar color to match Figma
- Fix Operations page spacing
- Change Operations background color to match Figma

This PR will probably cause catastrophic merge conflicts if merged before the connections PR, will fix the conflicts on this branch after connections PR is merged in

### CODE REVIEW

**Comment by ArulArora** [comment]
There seems to be an error when running the branch. "Cannot find module 'react-loader-spinner'. Might be caused by something we merged in with Darren's PR.

Let me know if this is only happening on my end.

**Comment by kevincheng0** [comment]
> There seems to be an error when running the branch. "Cannot find module 'react-loader-spinner'. Might be caused by something we merged in with Darren's PR.
> 
> Let me know if this is only happening on my end.

@ArulArora did you run `npm install` before running the branch? It works for me

**Comment by ArulArora** [comment]
I got it to work, it was on my end oops lol

Your page looks great, however there seems to be changes that messed up Darren's connections page. The width of his page changed with your commits not sure how. Currently on the main branch, his page's width looks fine but not on this branch.

Can you take a look at fixing this when you get a chance?

**Comment by kevincheng0** [comment]
Hmm ok, I fixed some sizings on the main page to work on all screen sizes, I'll check it out

**Pull request merged**
